# Generated by Django 3.2.8 on 2021-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100000),
        ),
    ]
