# Generated by Django 3.2.7 on 2021-10-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0004_delete_carttotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
