# Generated by Django 3.2.7 on 2021-10-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0005_carttotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartTotal',
        ),
    ]
