# Generated by Django 3.2.7 on 2021-10-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0006_auto_20211022_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
