# Generated by Django 3.2.7 on 2021-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffeeShop', '0007_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=100000)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
