# Generated by Django 3.2.8 on 2021-10-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
