# Generated by Django 3.2.8 on 2021-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeShop', '0010_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
